config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[create]
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates_length_of :comment, minimum: 6
  validates :movie, uniqueness: { scope: :list, message: 'Bookmark already exits' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: { message: 'cannot be blank' }, numericality: { only_integer: true }
  validates :rating, numericality: { in: 1..5 }
  validates :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[destroy]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list_id = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list_id)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
# Controller for lists
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[create]

  # def new
  #   @review = Review.new
  #   @list = List.find(params[:list_id])
  # end

  def create
    @review = Review.new(review_params)
    # @list = List.find(params[:list_id])
    @review.list_id = @list.id
    if @review.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @list_id = @review.list

    @review.destroy
    redirect_to list_path(@list_id)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_card.html.erb
<div class="card-trip">
  <img src=<%= bookmark.movie.poster_url %> />
  <div class="card-trip-infos">
    <div class="div">
      <h2><%= bookmark.movie.title %> - <%= bookmark.movie.rating %> <i class="fa-solid fa-star" style="color: #ffd43b;"></i></h2>
      <%# <% bookmark = Bookmark.find_by(movie: movie) %>
      <p><%= bookmark.movie.overview %></p>
      <div class="d-flex mt-2 justify-content-between">
        <div class="p-1">
          <p><i class="fa-solid fa-quote-left"></i> <strong><%= bookmark.comment%></strong></p>
        </div>
        <div class="p-1">
          <%= link_to bookmark_path(bookmark),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-regular fa-trash-can" style="color: #d23433"></i>
        <% end %>
        </div>
    </div>
    </div>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="row">
  <div class="container col-6 p-8">
  <h1>Create new Bookmark</h1>
  <%= render "form", list: @list, bookmark: @bookmark %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch List</title>
    <link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/512/3418/3418886.png">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%# <div class="container col-6"> %>
      <%= yield %>
    <%# </div> %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>');">
  <div class="container">
    <h1><strong><%= list.name %></strong></h1>
    <% if list.movies.count == 1 %>
    <div class="btn btn-flat">
      <%= "#{list.movies.count} Movie" %>
    </div>
    <% else %>
      <div class="btn btn-flat">
      <%= "#{list.movies.count} Movies" %>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<%= render "shared/banner" %>
<br>
<div class="cards">
  <% @lists.each do |list| %>
  <div class="card-category"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
    <%= link_to list.name, list_path(list) %>
  </div>
<% end %>
</div>

app/views/lists/new.html.erb
<div class="container col-6">
  <h1>Create a new List</h1>
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<%= render "lists/banner", list: @list %>

<div class="d-flex flex-row-reverse">
    <div class="p-4">
      <%= link_to "Add new bookmark", new_list_bookmark_path(@list), class: "btn btn-flat" %>
    </div>
</div>

<div class="d-flex flex-column justify-content-around">
<div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <%= render "bookmarks/card", list: @list, bookmark: bookmark %>
  <% end %>
</div>

<div class="py-4">
  <hr>
</div>

<div class="p-4">
  <%= render "reviews/show" %>
</div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [list, review] do |f| %>
  <%= f.input :comment %>
  <%# <%= f.input :rating %>
  <%= f.input :rating, collection: (1..5).to_a, input_html: {data: {controller: "star-rating"}} %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/reviews/_show.html.erb
<div class="d-flex justify-content-around">
  <div class="col-4">
    <h3>Reviews</h3>
    <% @list.reviews.each do |review| %>

    <div class="div">
      <% review.rating.times do %>
        <i class="fa-solid fa-star" style="color: #ffd43b;"></i>
      <% end %>
      <div class="d-flex mt-2 justify-content-between">
      <div class="div">
        <%= review.comment %>
      </div>
      <div style="text-decoration:none">
        <%= link_to "Delete", review_path(review), data: {turbo_method: :delete}%>
      </div>
    </div>
      <hr>
    </div>
    <% end %>
  </div>

  <div class="bg-light bg-gradient p-4 col-5 align-self-center">
    <h2>Add your review</h2>
    <%= render "reviews/form", review: @review, list: @list %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://149512919.v2.pressablecdn.com/wp-content/uploads/2021/12/philly-movies-hero-banner.jpg);">
  <div class="container">
    <h1><strong>Watch List</strong></h1>
    <p>Save any kind of movie</p>
    <%= link_to "Create a list", new_list_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by Iratxe</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <img src="https://cdn-icons-png.flaticon.com/512/3418/3418886.png" />
      <%# <%= cl_image_tag("popcorn_icon") %>
      <strong>Watch List</strong>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>